#!/usr/bin/perl

while ($line = <STDIN>) {
    $nfloor = 0;
    chomp $line;

    @floors = split('', $line);
    foreach $floor (@floors) {
        if ($floor eq '(') {
            # Up one floor
            $nfloor++;
        } elsif ($floor eq ')') {
            # Down one floor
            $nfloor--;
        }
    }
}

print($nfloor);