#!/usr/bin/python3

import sys
import re
from collections import defaultdict

aunties = []
finalsue = []

class Sue:
    def __init__(self, group):
        self.attributes = defaultdict(dict)
        self.attributes[group(1)] = int(group(2))
        self.attributes[group(3)] = int(group(4))
        self.attributes[group(5)] = int(group(6))

def read_input(stdin):
    for line in stdin:
        line = line.rstrip()
        match = re.match('Sue \d+: (\w+): (\d+), (\w+): (\d+), (\w+): (\d+)', line)
        aunties.append(Sue(match.group))

read_input(sys.stdin)

target_sue = {'children' : 3,
              'cats' : 7,
              'samoyeds' : 2,
              'pomeranians' : 3,
              'akitas' : 0,
              'vizslas' : 0,
              'goldfish' : 5,
              'trees' : 3,
              'cars' : 2,
              'perfumes' : 1}

index = 1
for sue in aunties:
    flag = True
    for attribute in sue.attributes.keys():
        if attribute in ['cats', 'trees']:
            if sue.attributes[attribute] <= target_sue[attribute]:
                flag = False
                break
        elif attribute in ['pomeranians', 'goldfish']:
            if sue.attributes[attribute] >= target_sue[attribute]:
                flag = False
                break
        elif sue.attributes[attribute] != target_sue[attribute]:
            flag = False
            break

    if flag == True:
        print (index)
        break
    index += 1

