#!/usr/bin/python

import re

# Uncomment for Part 2

def main():
	psswrd = list("hxbxwxba")
	#psswrd = list("hxbxxyzz")
	length = len(psswrd)
	index = length - 1

	while True:
		if psswrd[index] == 'z':
			psswrd[index] = 'a'
			index -= 1
			continue
		else:
			psswrd[index] = chr(ord(psswrd[index]) + 1) 

		if (index != length - 1): index = length - 1
		if(valid_pass(psswrd)): break

	print ''.join(psswrd)


def valid_pass(password):
	length = len(password)
	prev_char = ''
	letters_in_a_row = 1

	flag = False
	ascending_flag = False

	# Double letters twice
	if re.match(r'.*?(.)\1.*?(.)\2.*', ''.join(password)):
		flag = True
	else:
	   return False

	for i in range(length):
		if password[i] in ['i', 'o', 'l']: return False
		if i != 0 and ord(prev_char) + 1 == ord(password[i]):
			letters_in_a_row += 1
			if letters_in_a_row == 3:
				return flag and True
		else:
			letters_in_a_row = 1

		prev_char = password[i]

main()