#!/usr/bin/perl

while ($line = <STDIN>) {
    $nfloor = 0;
    chomp $line;

    @floors = split('', $line);
    $position = 1;
    foreach $floor (@floors) {
        if ($floor eq '(') {
            # Up one floor
            $nfloor++;
        } elsif ($floor eq ')') {
            # Down one floor
            $nfloor--;
        }
        last if ($nfloor == -1);
        $position++;
    }
}

print("$nfloor\n");
print("$position\n");