#!/usr/bin/python3

from json import loads
import sys

def parse(jsn):
    if isinstance(jsn, int):
        return jsn
    elif isinstance(jsn, list)
    :
        return sum(map(parse, jsn))
    elif not isinstance(jsn, dict):
        return 0
    #elif 'red' in jsn.values():
    #    return 0

    return parse(list(jsn.values()))

print(parse(loads(sys.stdin.read())))