#!/usr/bin/python

import sys, re

# Uncomment for part 2

word = "'a'+'b'"
total = 0
total += len(word) - len(eval(word))

for word in sys.stdin.readlines():
	word = word.rstrip("\n")
	#word = '"' + re.sub(r'(\W)', r'\\\1', word) + '"' 
	total += len(word) - len(eval(word))
	total += len(word) - len(eval(word))

total += len(word) - len(eval(word))
print(total)
